# Generated by Django 3.2 on 2021-11-19 14:29

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namaLengkap', models.CharField(max_length=100)),
                ('ttl', models.DateField()),
                ('gender', models.CharField(max_length=20)),
                ('handphone', models.IntegerField()),
                ('fotoProfile', models.ImageField(blank=True, null=True, upload_to=api.models.productFile)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UMKM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namaToko', models.CharField(max_length=100)),
                ('fotoProfile', models.ImageField(blank=True, null=True, upload_to=api.models.productFile)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
