# Generated by Django 3.2.9 on 2021-11-25 08:57

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_cart_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='userid',
        ),
        migrations.AddField(
            model_name='cart',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.productFile),
        ),
        migrations.AddField(
            model_name='cart',
            name='namaItem',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='namaToko',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
