# Generated by Django 3.2.9 on 2021-11-27 04:50

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20211125_0907'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namaPembeli', models.CharField(max_length=100)),
                ('noHP', models.CharField(max_length=100)),
                ('emailPembeli', models.CharField(max_length=100)),
                ('catatanPenjual', models.CharField(blank=True, max_length=500, null=True)),
                ('totalPembelian', models.IntegerField(null=True)),
                ('buktiPembayaran', models.ImageField(blank=True, null=True, upload_to=api.models.productFile)),
            ],
        ),
        migrations.CreateModel(
            name='Pengiriman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.CharField(max_length=100)),
                ('deskripsi', models.CharField(max_length=100)),
                ('harga', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('totalPrice', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(max_length=100)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product')),
                ('orderid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.order')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.seller')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.customer')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='jenisPengiriman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pengiriman'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product'),
        ),
    ]
