# Generated by Django 3.2.9 on 2021-11-28 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20211127_0551'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='alamat',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
